kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}