kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  - name: port1
    port: {{ .Values.service.port1 }}
    targetPort: {{ .Values.service.port1 }}
  - name: port2
    port: {{ .Values.service.port2 }}
    targetPort: {{ .Values.service.port2 }}
