kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
